id: P003020
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:34:45.592112
source_metadata:
  id: bdr:W1KG25210
  title: འདུལ་བ་ལས་ཆོག་རྣམ་རྒྱལ་གསེར་མདོག
  author: ''
  volumes:
    5ce4616ec66c457a95a66a93f3e5fb3e:
      image_group_id: I1KG25212
      title: ''
      volume_number: 1
      total_pages: 402
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
